---
name: 'Build Docker Images :latest'

on:
  push:
    branches: [ master ]
    

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare Base Build Metadata | DockerHub
        id: meta_base_dockerhub
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ secrets.DOCKER_USERNAME }}/borgmatic
          tags: |
            type=ref,event=branch
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Prepare Base Build Metadata | GHCR
        id: meta_base_ghcr
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/borgmatic-collective/borgmatic
          tags: |
            type=ref,event=branch
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build base
        uses: docker/build-push-action@v3
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./base
          file: ./base/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ steps.meta_base_ghcr.outputs.tags }}

 